USE GREY_GOOSE;

SHOW TABLES;


SELECT COUNT(*) FROM BUSINESS;
SELECT COUNT(*) FROM CUSTOMER;
SELECT COUNT(*) FROM WINTER_INTERNSHIP WHERE CLEAR_DATE != 0000-00-00;

DESC BUSINESS;
DESC CUSTOMER;
SELECT *FROM BUSINESS;
SELECT *FROM CUSTOMER;
SELECT *FROM WINTER_INTERNSHIP;

DESC WINTER_INTERNSHIP;